### ISSUE TITLE
Missing shortcut add-ons

### ISSUE THREAD

**Issue by horneydonkey10** [Helly1206/skin.xonfluence#12]
First off, I love your skin it is awesome. So I created my own build on my Windows computer but, whenever I back up and restore to my android tv box everything restores except my add-on shortcuts...the text remains but the icon is missing, so I can click on the text and it'll take me to the ad on there is just no add on picture

**Comment by horneydonkey10** [comment]
Please help me resolve this issue, thanks

**Comment by horneydonkey10** [comment]
So the way I just figured out is to make all your shortcuts as favorites and when creating shortcuts you go to shortcut folder to add them

**Comment by horneydonkey10** [comment]
Well I guess that only works for shortcut like widgets. For example, if you want to save as a favorite her place inside Phoenix that icon will show up on the restore but the Phoenix add on icon that you saved under favorites will not show up. Sill need help with this issue. Thanks

**Comment by Helly1206** [comment]
I think it has to do with paths in your settings.xml file. I can reopen if you like, but I'll close it for now
