### ISSUE TITLE
Widgets not highliting under TV Shows

### ISSUE THREAD

**Issue by wolf01d** [Helly1206/skin.xonfluence#16]
Hi,

I have noticed a problem when you have a main menu item as TV Shows and you set your widget set as recent episodes and widget format as thumbnail.
When you try to highlight the episode there is no highlight or arrow at the side of the widgets above the menu. This is ok if you select poster at the widget format.

I am using Kodi 17: on windows and raspberry Pi and I have the same problem on both.

Thanks for this great skin.
Wolf.
![tvshows-posterformat](https://cloud.githubusercontent.com/assets/22368892/23175525/97c10992-f857-11e6-87b1-df7b92c223a5.PNG)
![tvshows-thumbformat](https://cloud.githubusercontent.com/assets/22368892/23175526/97c80954-f857-11e6-9973-6106874d7914.PNG)

**Comment by Helly1206** [comment]
Hi, 

thanks for noticing this issue. I found a typo which solves this problem. Will be solved in 3.3.17 which I hope to release in a few days. If you want to solve it yourself before: [http://forum.kodi.tv/showthread.php?tid=238630&pid=2545485#pid2545485](url)

I'm closing this issue now.

Helly.
