### ISSUE TITLE
widget limit

### ISSUE THREAD

**Issue by johno21** [Helly1206/skin.xonfluence#17]
I’m on the latest version 3.3.18. When I set a custom widget from favourites I only get 10 thumbnails, in the past it was 20 I think. Any way of changing this to more than 10?

**Comment by Helly1206** [comment]
You can set it at: Skin settings -> Home menu -> Custom widgets limit amount


Thanks,

Helly.

________________________________
Van: johno21 <notifications@github.com>
Verzonden: maandag 19 juni 2017 14:09:24
Aan: Helly1206/skin.xonfluence
CC: Subscribed
Onderwerp: [Helly1206/skin.xonfluence] widget limit (#17)


I’m on the latest version 3.3.18. When I set a custom widget from favourites I only get 10 thumbnails, in the past it was 20 I think. Any way of changing this to more than 10?

**Comment by Helly1206** [comment]
Think this solves the issue, so I'll close.
