### ISSUE TITLE
snow effect

### ISSUE THREAD

**Issue by johno21** [Helly1206/skin.xonfluence#19]
hi is it possible to have the snow effect on normal backgrounds without choosing the holiday theme as this changes all the backgrounds. if so is there a line i can add to a file?

thanks in advance

**Comment by jdig4240** [comment]
This is not an "Issue". Support thread is here: https://forum.kodi.tv/showthread.php?tid=315391

**Comment by Helly1206** [comment]
I agree this is not an issue. You cannot change it by one of the settings. You surely can do this by editing the code. As I mentioned before in the support thread, I don't give suggested code changes (I have negative experience with this), but maybe someone else on the thread will.

Helly.
