### ISSUE TITLE
Own wallpapers disappearing after each update

### ISSUE THREAD

**Issue by TheFeliks** [Helly1206/skin.xonfluence#24]
After each automatic update my wallpapers are bing deleted. I am keeping plenty of my own wallpapers in addons\skin.xonfluence\backgrounds

I can disable automatic update, but it is usually not the best way of doing things. Is there another way to prevent it? Fix maybe?

**Comment by Helly1206** [comment]
You can place the wallpapers in a different folder (not the skin folder but any other folder on your system) and select alternate background folder in the skin settings - backgrounds menu. Now setup your backgrounds for once and they are not deleted anymore on a skin update.

For Leia Xonfleunce will have a major update which may be released in a few weeks time (Xonfluence version 4.0.0). For this update the background setting will also change (using resources), but the alternate background folders option stays in.

Helly.
