### ISSUE TITLE
Home Menu Item Auto Scroll Question

### ISSUE THREAD

**Issue by kodi8r** [Helly1206/skin.xonfluence#26]
Hi thanks for a great customizable skin. Been using it awhile now but with so many great options I havent yet fully learned all its capabilities. Is there a way to have a home menu item auto scroll when it's label is too long to be fully visible? Thanks in advance.

**Comment by Helly1206** [comment]
Hi,

good remark. I will add it in the next release for Leia.

For krypton I added in the IncludesMainMenu.xml file in this repository. Just update this file to scroll the labels.

Helly.

**Comment by kodi8r** [comment]
Hi, 

Thank you so much for your reply. Unfortunately, this did not resolve the issue for me. Just a little info on my scenario: 

kodi krypton 17.6
xonfluence skin 3.3.19
helly repo 0.2.4
theme: skin default
colours: skin default
fonts: Larger font size
home menu items 1 title changed from Weather to MOVIES & TV SHOWS in all caps

only the letters MOVIES & TV S are visible with no auto scroll function happening. 

I updated IncludesMainMenu.xml file from repository as instructed so not sure if there is something I'm not understanding?

thanks
kodi8r

**Comment by Helly1206** [comment]
I didn't change the xml file for krypton, only for Leia . You need to do that by hand if you want to.

Add <scroll>true</scroll> at lines: 137, 165, 178, 222, 263, 276 by hand, restart kodi and it should work.

Keep in mind the scrolling for labels doesn't look very nice in Kodi (I can't help it), I would suggest to use shorter names.

Helly.
________________________________
Van: kodi8r <notifications@github.com>
Verzonden: maandag 9 april 2018 11:00
Aan: Helly1206/skin.xonfluence
CC: Ivo Helwegen; State change
Onderwerp: Re: [Helly1206/skin.xonfluence] Home Menu Item Auto Scroll Question (#26)


Hi,

Thank you so much for your reply. Unfortunately, this did not resolve the issue for me. Just a little info on my scenario:

kodi krypton 17.6
xonfluence skin 3.3.19
helly repo 0.2.4
theme: skin default
colours: skin default
fonts: Larger font size
home menu items 1 title changed from Weather to MOVIES & TV SHOWS in all caps

only the letters MOVIES & TV S are visible with no auto scroll function happening.

I updated IncludesMainMenu.xml file from repository as instructed so not sure if there is something I'm not understanding?

thanks
kodi8r
