### ISSUE TITLE
Old Bubbles from confluense starting on homescreen of xconfluence

### ISSUE THREAD

**Issue by Richard6360** [Helly1206/skin.xonfluence#29]
Hello Helly1206, I have the old style bubble animation on the homescreens of xconfluence

in the old xbmc or early kodi versions there was a setting to set it on (default was off i believe)

cant find anything to turn it back off. when switching back and forth to different skins its off but ON again on switching back to xconfluence

any idea where in the repo to look for this setting? Cant find it in guisettings.xml.

Bedankt alvast :-)

**Comment by Richard6360** [comment]
found it!!!!
in IncludesBackgroundEffect.xml i set the <visible> flag to false on all counts (with the raindrop only)
and after reboot its gone !
Why is this not in the settings anymore ?

**Comment by Richard6360** [comment]
Its not in the settings of xconfluence

Op za 24 nov. 2018 09:21 schreef Helly1206 <notifications@github.com:

**Comment by Richard6360** [comment]
Strenge, in the Dutch settings or is Nog there. I switches to english to
show jou a picture of chat. And there it was!

Very strange.  I let kodi in English now 😀
Thanks!

Op za 12 jan. 2019 14:22 schreef Helly1206 <notifications@github.com:

**Comment by Helly1206** [comment]
The setting is there in Dutch. I see now that it is translated incorrectly. It is called: 'Activeer aflevering miniatuur' for one reason or another.

Consider it fixed in the next release.

Helly.

**Comment by Richard6360** [comment]
Ok I wasn't looking there. I saw that it wasn't working. Maybe because off
the manual change I had made in the guise xml. I will set this back to try
it.

I am seeking a way to read back the return of a json command of title and
playtime etc. I did this in mit appinventor for android. But i want to have
it in html/js or ajax or something. Can you help with that.

I can help with translating if you like.


Op zo 13 jan. 2019 08:34 schreef Helly1206 <notifications@github.com:
