### ISSUE TITLE
Xonfluence not compatibile with K18 RC5

### ISSUE THREAD

**Issue by TheFeliks** [Helly1206/skin.xonfluence#31]
Hi.

Just installed K18 RC5 and got the standard skin on it... it shows that Xonfluence is not compatibile with this version of Kodi. 
It works perfectly fine with RC3 and RC4 so I rolled back to RC4.

Just wanted to let you know about this issue. Thanks

**Comment by Helly1206** [comment]
Hi,

There is indeed a compatibility issue.

See the forum:
[https://forum.kodi.tv/showthread.php?tid=315391&pid=2805388#pid2805388](url)

Will be fixed in the next release.

Helly.
