### ISSUE TITLE
Subtitle button make the mouse click not working

### ISSUE THREAD

**Issue by Sopor-** [Helly1206/skin.xonfluence#32]
When playing video the menu at the lower right won't work as it should. I'm using the mouse and to get them to work i need to move the mouse pointer around to the right of the menu buttons to get them to work. If i use the left side only the first button get highlighted and the three others won't. Even if the first button get highlighted non of the buttons work.

It seems to have something to do with the subtitle button. If i move the mouse this will get highlighted but nothing happens if i press on it. When i then move to the next button it seems to have disabled the mouse click.

If i change skin to Confluence it will bring up the subtitle settings as it is supposed to do.

Kodi 18 RC5 x64

**Comment by Helly1206** [comment]
Thank for the thorough explanation. 

The issue is found. Will be solved in the next release.
