### ISSUE TITLE
Text in directory

### ISSUE THREAD

**Issue by TheFeliks** [Helly1206/skin.xonfluence#33]
Hi,

I found another issue. Text in directory is much lower than it suppose to be for some reason.
https://prnt.sc/m7fvdq

This text should be displayed from the top of the directory instead of 4-5 levels lower.

Edit few hours later.
I see that "Please Wait" with circle is at the bottom instead of the top :)
http://prntscr.com/m7ow3x

**Comment by Helly1206** [comment]
Hi,

first issue has to do with a fixed list change, see [https://forum.kodi.tv/showthread.php?tid=315391&pid=2810850#pid2810850](url)

Second one I just changed its position and I don't have plans to move it back. I see it may overlap the floor return buttons. I will solve this overlapping issue.

Helly.

**Comment by h45rd** [comment]
Just my 2c: after being surprised by the position change at first, I actually prefer it now :)

While I am at it.. thanks for continually keeping up with Kodi development and improving the skin, Helly.
Don't know what I would do without it.
Tried using Estuary for a few days while you were catching up to the new RC, and... well... let's just better not talk about that dark time :D


Regards,
h45rd
