### ISSUE TITLE
Change Skal Inställningar to Skalinställningar

### ISSUE THREAD

**Issue by Sopor-** [Helly1206/skin.xonfluence#36]
I couldn't find it in the swedish strings.po file. It need to be change on several places and this is one of them. Do you need them all or you can search for it?

![image](https://user-images.githubusercontent.com/5789283/51794011-00ada080-21ca-11e9-9565-67472c420b15.png)

The correct word should be `Skalinställningar`.

**Comment by Helly1206** [comment]
That is becuase this word isp robably from the main springs.po file, not the additional strings.po for xonfluence (I cannot find this word in my strings.po), or probably composed form 2 words. I cannot change that per language.

Helly.
