### ISSUE TITLE
Can't update Xonfluence

### ISSUE THREAD

**Issue by Sopor-** [Helly1206/skin.xonfluence#37]
It seems that i can't update the skin. I only get a message that it has failed. I have tried to change it back to the original Kodi skin but when i chose the Xonfluence and try to update it i get failed again and the skin will be changed to None.

It seems that i need to change skin to something else than Xonfluence and now i can update Xonfluence and when i have updated it i can change back to the Xonfluence skin again. I have no idea if this is a skin or Kodi related issue or maybe both?

**Comment by Helly1206** [comment]
Is an issue with kodi for Windows. Not skin related
[https://forum.kodi.tv/showthread.php?tid=315391&pid=2795075#pid2795075](url)
