### ISSUE TITLE
Left menu will close if the mouse pointer moves too far up or down

### ISSUE THREAD

**Issue by Sopor-** [Helly1206/skin.xonfluence#38]
If i move the mouse pointer to the left to open the side menu and i move it above the red line, the menu will close. Same thing if i go down above the last button it will close the menu. If i move the mouse over the blue text (menu titles) it will close the menu if i'm to slow to move the mouse. Quiet annoying...
If i do the same in the `Confluence` skin it will continue to be open.

![image](https://user-images.githubusercontent.com/5789283/52084941-84d59e80-25a3-11e9-92d4-b5bca24afc21.png)

**Comment by Helly1206** [comment]
You should click on the label to unfold the side blade. You opened it with the arrow keys and then use the mouse for navigation. If you use the keyboard to open, you also have to use the keys to navigate. If you use the mouse to open, use can use the mouse to navigate. I don't think I can change this behavior.

**Comment by Sopor-** [comment]
Arrow keys?! I use the mouse only...

**Comment by Helly1206** [comment]
You're right. Found the cause. Will be fixed in the next release.
