### ISSUE TITLE
Favourites window not popping up. 

### ISSUE THREAD

**Issue by Lantash77** [Helly1206/skin.xonfluence#55]
Tested on Rpi4 libreelec, Android and win10. It's adding items to favourites, but not showing whe star button clicked.

**Comment by jmh2002** [comment]
See my post in the official Xonfluence support thread here to check if it solves your problem:

https://forum.kodi.tv/showthread.php?tid=346302&pid=3052595#pid3052595

**Comment by Lantash77** [comment]
Perfect, Thank you.
