### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by Arthur1967** [Helly1206/skin.xonfluence#59]
When I save something to favorites and then I click on favorites nothing shows I know it's me but can you help me out thank you I love the skin

**Comment by MTouchet81** [comment]
It does that to me sometimes as well some addons will disable addons is why
it done it to me but mine was with super favorites not favorites you sure
you have it routed right in the menu cuz I believe there is two ways to get
favorits one under common ya know the commands and then scroll down through
movies and tv library and there’s another one let me try it and see if I
can figure out what your doing r unless you can maybe video or screen shot
sometimes clearing cache and rebooting will help but have you tried using
super favorites it’s in the djthemes addon if your familiar and use
dabutcher repo has add that source you can add any addon find dj themes and
then install super favorites just a suggestion cuz favorites gives you one
list for all media as to where super favorites has multiple plus your able
to configure it to also access your favorites through Superfavourites

**Comment by Arthur1967** [comment]
I’m using auto widget and I have to save it to my favorites before it will
show up in a widget

**Comment by MTouchet81** [comment]
Oh wow this came to my email was wondering why I got it lol didn’t know it
was through the actual GitHub app I’m still learning as well but was just
helping best way I could hope you get the issue resolved

**Comment by Arthur1967** [comment]
I got it figured out you just have to go to skin settings and then down the
script and install the script and  enable Favorites for some reason the
script wasn’t included but it’s all good to go now I love the skin thank you

**Comment by MTouchet81** [comment]
Sweet glad you got it figured out see we can learn from each other I figure
out new stuff all the times and addons come and go and some go down is
anyone else having issues with fen like it works on my series x which is
weird usually get more errors on there but it will not work on either
Firestick tablet or fire tv figured they would get it straightened out just
thought I’d ask usually it’s to do with the python when I have issues I
have the repo in the build I’m using but it fails everytime so does the my
accounts fen works great when it’s running I’ve learned to turn down
scraper to low as possible and it flies man sometimes it’s not good if
there’s not a lot of links but usually not an issue my bad kinda got off
subject a sec I love this stuff really wish I knew how to do the xmls or
whatever to customize my own I do it the bootleg way with icons wallpapers
and even fonts I just find the one I want then swap the names so I’m
technically not changing the coding or what have you just swapping it out
but man I’m getting good at customizing like I want just limited I wanna be
able to do my own custom stuff like you badass developers do I wish there
was a class on this shit or something during covid and I was in a coma and
bed ridden fir2 years after I awoke I got into this stuff learned a lot but
coding and stuff is way beyond me I’m not smart enough I guess

**Comment by Grossdm** [comment]
> 

Thank you! That worked for me.
